name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation", "good first issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Documentation contributions are highly valued. 📚

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - "Getting Started / Tutorial"
        - "API Reference"
        - "Concepts / Architecture"
        - "Examples"
        - "Troubleshooting"
        - "Contributing Guide"
        - "README"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's the problem?
      description: What is unclear, missing, or incorrect in the current documentation?
      placeholder: The documentation for XYZ doesn't explain...
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: How could the documentation be improved?
      placeholder: It would be helpful to add...
    validations:
      required: true

  - type: input
    id: page
    attributes:
      label: Page/File Location
      description: Which page or file needs improvement?
      placeholder: "docs/getting-started/quickstart.md"

  - type: dropdown
    id: willing-to-help
    attributes:
      label: Can you help fix this?
      description: Documentation PRs are a great way to start contributing!
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance on where to edit"
        - "No, I'm just reporting"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Screenshots, examples from other projects, etc.
