name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please note that the Ainalyn SDK is a **compiler, not a runtime**. Features must comply with platform boundaries.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: I'm trying to... but currently I have to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? Why don't they work?
      placeholder: I tried... but...

  - type: dropdown
    id: boundary-check
    attributes:
      label: Platform Boundary Compliance
      description: Does this feature comply with SDK boundaries? (No execution, billing, or platform authority)
      options:
        - "Yes, this is a compiler/validation/export feature"
        - "No, this involves execution or runtime behavior"
        - "I'm not sure"
    validations:
      required: true

  - type: textarea
    id: api-example
    attributes:
      label: API Example
      description: Show what the API would look like if this feature existed.
      placeholder: |
        ```python
        # Example usage
        agent = AgentBuilder("MyAgent")...
        ```

  - type: dropdown
    id: willing-to-help
    attributes:
      label: Are you willing to help implement this?
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance"
        - "No, I'm just suggesting"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Links to similar features in other projects, etc.
