openapi: 3.0.0
info:
  title: AI Counseling API
  version: 1.0.0
  description: |
    AI Counseling Service API - Emotional support and guidance powered by AI.

    ## Features
    - Real-time emotional state detection
    - Multi-style counseling (supportive, cognitive, solution-focused)
    - Streaming and non-streaming responses
    - Session management
    - Conversation context preservation
    - Crisis detection and safety protocols
  contact:
    name: CoreNovus API Support
    email: api@corenovus.com

servers:
  - url: https://api.corenovus.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

tags:
  - name: counseling
    description: Counseling session operations
  - name: sessions
    description: Session management
  - name: styles
    description: Counseling style management

paths:
  /api/v1/counseling/message:
    post:
      tags:
        - counseling
      summary: Send counseling message
      description: Send a message and receive AI counseling response with emotional analysis
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CounselingMessageRequest'
      responses:
        '200':
          description: Response generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CounselingMessageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/counseling/stream:
    post:
      tags:
        - counseling
      summary: Send counseling message (streaming)
      description: Send a message and receive response via Server-Sent Events
      operationId: streamMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CounselingMessageRequest'
      responses:
        '200':
          description: Stream started
          content:
            text/event-stream:
              schema:
                type: string
                format: binary

  /api/v1/counseling/sessions:
    get:
      tags:
        - sessions
      summary: List counseling sessions
      description: Retrieve all counseling sessions
      operationId: getSessions
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
        - name: includeArchived
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Sessions retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsListResponse'

    post:
      tags:
        - sessions
      summary: Create new session
      description: Start a new counseling session
      operationId: createSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSessionRequest'
      responses:
        '201':
          description: Session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSessionResponse'

  /api/v1/counseling/sessions/{sessionId}:
    get:
      tags:
        - sessions
      summary: Get session details
      description: Retrieve session information with conversation history
      operationId: getSession
      parameters:
        - $ref: '#/components/parameters/sessionId'
        - name: includeMessages
          in: query
          schema:
            type: boolean
            default: true
        - name: messageLimit
          in: query
          schema:
            type: integer
            default: 50
      responses:
        '200':
          description: Session details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionDetailResponse'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - sessions
      summary: Delete session
      description: Permanently delete a counseling session
      operationId: deleteSession
      parameters:
        - $ref: '#/components/parameters/sessionId'
      responses:
        '204':
          description: Session deleted
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/counseling/styles:
    get:
      tags:
        - styles
      summary: Get counseling styles
      description: Retrieve available counseling styles and their descriptions
      operationId: getStyles
      responses:
        '200':
          description: Styles retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StylesResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    sessionId:
      name: sessionId
      in: path
      required: true
      schema:
        type: string
      description: Session ID

  schemas:
    CounselingStyle:
      type: string
      enum:
        - supportive
        - cognitive
        - solution_focused
        - motivational
        - mindfulness
      description: |
        Counseling approach:
        - supportive: Empathetic listening and emotional validation
        - cognitive: Focus on thought patterns and reframing
        - solution_focused: Goal-oriented problem solving
        - motivational: Encouragement and behavioral change
        - mindfulness: Present-moment awareness techniques

    EmotionalState:
      type: object
      properties:
        primary:
          type: string
          description: Primary detected emotion
          example: anxious
        secondary:
          type: array
          items:
            type: string
          description: Secondary emotions
        intensity:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: Emotional intensity (0-1)
        valence:
          type: number
          format: float
          minimum: -1
          maximum: 1
          description: Emotional valence (-1 negative to 1 positive)
        confidence:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: Detection confidence

    SafetyAssessment:
      type: object
      properties:
        level:
          type: string
          enum:
            - safe
            - caution
            - concern
            - crisis
          description: Safety level assessment
        indicators:
          type: array
          items:
            type: string
          description: Detected safety indicators
        recommendedAction:
          type: string
          description: Recommended follow-up action
        resources:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              type:
                type: string
              contact:
                type: string
          description: Crisis resources (if applicable)

    CounselingMessageRequest:
      type: object
      required:
        - message
        - counselingStyle
      properties:
        message:
          type: string
          minLength: 1
          maxLength: 5000
          description: User message
        sessionId:
          type: string
          description: Session ID (creates new session if not provided)
        counselingStyle:
          $ref: '#/components/schemas/CounselingStyle'
        language:
          type: string
          default: en
          description: Response language (e.g., en, zh-TW, ja)
        context:
          type: object
          properties:
            previousEmotions:
              type: array
              items:
                $ref: '#/components/schemas/EmotionalState'
            sessionGoals:
              type: array
              items:
                type: string
            userPreferences:
              type: object
              additionalProperties:
                type: string

    CounselingMessageResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                response:
                  type: string
                  description: AI counseling response
                sessionId:
                  type: string
                  description: Session ID
                emotionalAnalysis:
                  $ref: '#/components/schemas/EmotionalState'
                safetyAssessment:
                  $ref: '#/components/schemas/SafetyAssessment'
                suggestions:
                  type: array
                  items:
                    type: string
                  description: Follow-up suggestions
                metadata:
                  type: object
                  properties:
                    model:
                      type: string
                    processingTime:
                      type: number
                      format: float
                    tokens:
                      type: object
                      properties:
                        input:
                          type: integer
                        output:
                          type: integer

    CreateSessionRequest:
      type: object
      properties:
        title:
          type: string
          description: Session title (auto-generated if not provided)
        counselingStyle:
          $ref: '#/components/schemas/CounselingStyle'
        language:
          type: string
          default: en
        initialContext:
          type: string
          description: Initial context or concern

    CreateSessionResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                sessionId:
                  type: string
                title:
                  type: string
                createdAt:
                  type: string
                  format: date-time
                welcomeMessage:
                  type: string
                  description: Initial AI greeting

    SessionsListResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                sessions:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      counselingStyle:
                        type: string
                      lastActivity:
                        type: string
                        format: date-time
                      messageCount:
                        type: integer
                      emotionalTrend:
                        type: string
                        description: Overall emotional trend
                pagination:
                  $ref: '#/components/schemas/Pagination'

    SessionDetailResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                session:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    counselingStyle:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
                    updatedAt:
                      type: string
                      format: date-time
                messages:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      role:
                        type: string
                        enum:
                          - user
                          - assistant
                      content:
                        type: string
                      timestamp:
                        type: string
                        format: date-time
                      emotionalState:
                        $ref: '#/components/schemas/EmotionalState'
                insights:
                  type: object
                  properties:
                    emotionalJourney:
                      type: array
                      items:
                        $ref: '#/components/schemas/EmotionalState'
                    keyTopics:
                      type: array
                      items:
                        type: string
                    progress:
                      type: string

    StylesResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  bestFor:
                    type: array
                    items:
                      type: string
                    description: Situations this style works best for
                  techniques:
                    type: array
                    items:
                      type: string

    ApiResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        error:
          type: string
        message:
          type: string
        code:
          type: string

    Pagination:
      type: object
      properties:
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        hasMore:
          type: boolean

    ErrorResponse:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        message:
          type: string
        code:
          type: string
        details:
          type: object

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    TooManyRequests:
      description: Rate limit exceeded
      headers:
        Retry-After:
          description: Seconds until retry allowed
          schema:
            type: integer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - bearerAuth: []
