openapi: 3.0.0
info:
  title: Image Analysis API
  version: 1.0.0
  description: |
    AI Image Analysis Service API - Analyze images and get intelligent responses.

    ## Features
    - Upload image files or provide image URLs
    - Ask questions about image content
    - Get detailed image descriptions
    - Object detection and recognition
    - Text extraction (OCR)
    - Multiple output formats (text, JSON, markdown)
  contact:
    name: CoreNovus API Support
    email: api@corenovus.com

servers:
  - url: https://api.corenovus.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

tags:
  - name: image-analysis
    description: Image analysis operations
  - name: history
    description: Analysis history operations

paths:
  /api/v1/image-analysis/analyze:
    post:
      tags:
        - image-analysis
      summary: Analyze image
      description: Upload an image or provide URL and ask questions about its content
      operationId: analyzeImage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: Image file (JPG, PNG, GIF, WebP)
                imageUrl:
                  type: string
                  format: uri
                  description: Image URL (alternative to file upload)
                question:
                  type: string
                  minLength: 1
                  maxLength: 1000
                  description: Question about the image
                outputFormat:
                  type: string
                  enum:
                    - text
                    - json
                    - markdown
                  default: text
                  description: Response format
                language:
                  type: string
                  default: en
                  description: Response language
                detailedAnalysis:
                  type: boolean
                  default: false
                  description: Enable detailed analysis mode
          application/json:
            schema:
              type: object
              required:
                - imageUrl
              properties:
                imageUrl:
                  type: string
                  format: uri
                  description: Image URL
                question:
                  type: string
                  maxLength: 1000
                outputFormat:
                  type: string
                  enum:
                    - text
                    - json
                    - markdown
                  default: text
                language:
                  type: string
                  default: en
                detailedAnalysis:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Analysis completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzeImageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/image-analysis/describe:
    post:
      tags:
        - image-analysis
      summary: Get image description
      description: Get a detailed description of the image content
      operationId: describeImage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                imageUrl:
                  type: string
                  format: uri
                detailLevel:
                  type: string
                  enum:
                    - brief
                    - standard
                    - detailed
                  default: standard
                  description: Description detail level
                language:
                  type: string
                  default: en
      responses:
        '200':
          description: Description generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeImageResponse'

  /api/v1/image-analysis/detect-objects:
    post:
      tags:
        - image-analysis
      summary: Detect objects
      description: Detect and identify objects in the image
      operationId: detectObjects
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                imageUrl:
                  type: string
                  format: uri
                confidenceThreshold:
                  type: number
                  format: float
                  minimum: 0
                  maximum: 1
                  default: 0.5
                  description: Minimum confidence threshold
                maxObjects:
                  type: integer
                  minimum: 1
                  maximum: 100
                  default: 20
                  description: Maximum objects to detect
      responses:
        '200':
          description: Objects detected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetectObjectsResponse'

  /api/v1/image-analysis/extract-text:
    post:
      tags:
        - image-analysis
      summary: Extract text (OCR)
      description: Extract text content from the image using OCR
      operationId: extractText
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                imageUrl:
                  type: string
                  format: uri
                language:
                  type: string
                  description: Expected text language (for better accuracy)
                preserveLayout:
                  type: boolean
                  default: false
                  description: Preserve original text layout
      responses:
        '200':
          description: Text extracted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractTextResponse'

  /api/v1/image-analysis/history:
    get:
      tags:
        - history
      summary: Get analysis history
      description: Retrieve past image analysis records
      operationId: getAnalysisHistory
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: sortBy
          in: query
          schema:
            type: string
            enum:
              - createdAt
              - type
            default: createdAt
        - name: sortOrder
          in: query
          schema:
            type: string
            enum:
              - asc
              - desc
            default: desc
      responses:
        '200':
          description: History retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisHistoryResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AnalyzeImageResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                answer:
                  type: string
                  description: AI response to the question
                confidence:
                  type: number
                  format: float
                  minimum: 0
                  maximum: 1
                  description: Response confidence score
                imageInfo:
                  $ref: '#/components/schemas/ImageInfo'
                relatedQuestions:
                  type: array
                  items:
                    type: string
                  description: Suggested follow-up questions
                metadata:
                  $ref: '#/components/schemas/AnalysisMetadata'

    DescribeImageResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                description:
                  type: string
                  description: Image description
                tags:
                  type: array
                  items:
                    type: string
                  description: Relevant tags
                categories:
                  type: array
                  items:
                    type: string
                  description: Image categories
                dominantColors:
                  type: array
                  items:
                    type: string
                  description: Dominant colors (HEX)
                imageInfo:
                  $ref: '#/components/schemas/ImageInfo'
                metadata:
                  $ref: '#/components/schemas/AnalysisMetadata'

    DetectObjectsResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                objects:
                  type: array
                  items:
                    $ref: '#/components/schemas/DetectedObject'
                totalCount:
                  type: integer
                  description: Total objects detected
                imageInfo:
                  $ref: '#/components/schemas/ImageInfo'
                metadata:
                  $ref: '#/components/schemas/AnalysisMetadata'

    ExtractTextResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                text:
                  type: string
                  description: Extracted text content
                blocks:
                  type: array
                  items:
                    type: object
                    properties:
                      text:
                        type: string
                      confidence:
                        type: number
                        format: float
                      boundingBox:
                        $ref: '#/components/schemas/BoundingBox'
                  description: Text blocks with positions
                language:
                  type: string
                  description: Detected text language
                confidence:
                  type: number
                  format: float
                  description: Overall OCR confidence
                metadata:
                  $ref: '#/components/schemas/AnalysisMetadata'

    AnalysisHistoryResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                        enum:
                          - analyze
                          - describe
                          - detect
                          - ocr
                      thumbnailUrl:
                        type: string
                        format: uri
                      question:
                        type: string
                      summary:
                        type: string
                      createdAt:
                        type: string
                        format: date-time
                pagination:
                  type: object
                  properties:
                    total:
                      type: integer
                    page:
                      type: integer
                    pageSize:
                      type: integer
                    hasMore:
                      type: boolean

    ImageInfo:
      type: object
      properties:
        width:
          type: integer
          description: Image width (pixels)
        height:
          type: integer
          description: Image height (pixels)
        format:
          type: string
          description: Image format
        size:
          type: integer
          description: File size (bytes)

    DetectedObject:
      type: object
      properties:
        name:
          type: string
          description: Object name
        confidence:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: Detection confidence
        boundingBox:
          $ref: '#/components/schemas/BoundingBox'
        attributes:
          type: object
          additionalProperties:
            type: string
          description: Additional attributes

    BoundingBox:
      type: object
      properties:
        x:
          type: number
          description: X coordinate (0-1 relative)
        y:
          type: number
          description: Y coordinate (0-1 relative)
        width:
          type: number
          description: Width (0-1 relative)
        height:
          type: number
          description: Height (0-1 relative)

    AnalysisMetadata:
      type: object
      properties:
        model:
          type: string
          description: AI model used
        processingTime:
          type: number
          format: float
          description: Processing time (seconds)
        timestamp:
          type: string
          format: date-time

    ApiResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        error:
          type: string
        message:
          type: string
        code:
          type: string

    ErrorResponse:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        message:
          type: string
        code:
          type: string
        details:
          type: object

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    PayloadTooLarge:
      description: File too large (max 20MB)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    UnprocessableEntity:
      description: Unable to process image
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - bearerAuth: []
