openapi: 3.0.0
info:
  title: AI Presentation API
  version: 1.0.0
  description: |
    AI Presentation Generation Service API - Create professional presentations with AI.

    ## Features
    - AI-generated presentations from prompts
    - Multiple themes and layouts
    - Image generation for slides
    - Real-time generation via WebSocket
    - Export to multiple formats (PPTX, PDF, HTML)
    - Template library
  contact:
    name: CoreNovus API Support
    email: api@corenovus.com

servers:
  - url: https://api.corenovus.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

tags:
  - name: presentation
    description: Presentation generation operations
  - name: templates
    description: Template management
  - name: export
    description: Export operations

paths:
  /api/v1/presentation/generate:
    post:
      tags:
        - presentation
      summary: Generate presentation
      description: Create a new AI-generated presentation from a topic or prompt
      operationId: generatePresentation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeneratePresentationRequest'
      responses:
        '202':
          description: Generation task accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneratePresentationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/presentation/tasks/{taskId}:
    get:
      tags:
        - presentation
      summary: Get generation task status
      description: Check the progress and result of a presentation generation task
      operationId: getTaskStatus
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
          description: Task ID
      responses:
        '200':
          description: Task status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/presentation/{presentationId}:
    get:
      tags:
        - presentation
      summary: Get presentation details
      description: Retrieve presentation details and slides
      operationId: getPresentation
      parameters:
        - name: presentationId
          in: path
          required: true
          schema:
            type: string
          description: Presentation ID
      responses:
        '200':
          description: Presentation details retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PresentationDetailResponse'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags:
        - presentation
      summary: Update presentation
      description: Update presentation content or settings
      operationId: updatePresentation
      parameters:
        - name: presentationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePresentationRequest'
      responses:
        '200':
          description: Presentation updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PresentationDetailResponse'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - presentation
      summary: Delete presentation
      description: Delete a presentation
      operationId: deletePresentation
      parameters:
        - name: presentationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Presentation deleted
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/presentation/{presentationId}/export:
    post:
      tags:
        - export
      summary: Export presentation
      description: Export presentation to various formats
      operationId: exportPresentation
      parameters:
        - name: presentationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExportRequest'
      responses:
        '200':
          description: Export completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/presentation/templates:
    get:
      tags:
        - templates
      summary: Get templates
      description: List available presentation templates
      operationId: getTemplates
      parameters:
        - name: category
          in: query
          schema:
            type: string
          description: Filter by category
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 50
      responses:
        '200':
          description: Templates retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplatesResponse'

  /api/v1/presentation/ws:
    get:
      tags:
        - presentation
      summary: WebSocket connection
      description: Establish WebSocket connection for real-time generation updates
      operationId: connectWebSocket
      parameters:
        - name: taskId
          in: query
          required: true
          schema:
            type: string
          description: Task ID to monitor
      responses:
        '101':
          description: Switching to WebSocket
        '400':
          description: Invalid request

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PresentationTheme:
      type: string
      enum:
        - professional
        - creative
        - minimalist
        - corporate
        - educational
        - startup
        - tech
        - nature
        - elegant
      description: Presentation theme

    SlideLayout:
      type: string
      enum:
        - title
        - title_content
        - two_columns
        - image_left
        - image_right
        - full_image
        - comparison
        - timeline
        - chart
        - quote
      description: Slide layout type

    ExportFormat:
      type: string
      enum:
        - pptx
        - pdf
        - html
        - png
        - jpg
      description: Export format

    GeneratePresentationRequest:
      type: object
      required:
        - topic
        - slideCount
      properties:
        topic:
          type: string
          minLength: 1
          maxLength: 500
          description: Presentation topic or prompt
        slideCount:
          type: integer
          minimum: 3
          maximum: 50
          default: 10
          description: Number of slides
        theme:
          $ref: '#/components/schemas/PresentationTheme'
        language:
          type: string
          default: en
          description: Content language
        audience:
          type: string
          description: Target audience
        style:
          type: object
          properties:
            tone:
              type: string
              enum:
                - formal
                - casual
                - persuasive
                - informative
              default: professional
            colorScheme:
              type: string
              description: Custom color scheme
            fontFamily:
              type: string
        includeImages:
          type: boolean
          default: true
          description: Generate images for slides
        includeCharts:
          type: boolean
          default: true
          description: Include charts and data visualizations
        outline:
          type: array
          items:
            type: string
          description: Custom outline (optional)
        additionalContext:
          type: string
          maxLength: 2000
          description: Additional context

    GeneratePresentationResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            taskId:
              type: string
              description: Task ID
            status:
              type: string
              enum:
                - queued
                - processing
                - completed
                - failed
            estimatedTime:
              type: integer
              description: Estimated completion time (seconds)
            wsUrl:
              type: string
              format: uri
              description: WebSocket URL for real-time updates

    TaskStatusResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            taskId:
              type: string
            status:
              type: string
              enum:
                - queued
                - processing
                - generating_outline
                - generating_content
                - generating_images
                - finalizing
                - completed
                - failed
            progress:
              type: integer
              minimum: 0
              maximum: 100
              description: Progress percentage
            currentStep:
              type: string
              description: Current processing step
            presentationId:
              type: string
              description: Presentation ID (when completed)
            previewUrl:
              type: string
              format: uri
              description: Preview URL (when completed)
            error:
              type: string
              description: Error message (when failed)

    Slide:
      type: object
      properties:
        id:
          type: string
        order:
          type: integer
          description: Slide order (1-based)
        layout:
          $ref: '#/components/schemas/SlideLayout'
        title:
          type: string
        content:
          type: object
          properties:
            text:
              type: string
            bulletPoints:
              type: array
              items:
                type: string
            notes:
              type: string
              description: Speaker notes
        media:
          type: object
          properties:
            imageUrl:
              type: string
              format: uri
            imagePrompt:
              type: string
              description: Prompt used for image generation
            chartData:
              type: object
              description: Chart configuration
        transition:
          type: string
          description: Slide transition effect

    PresentationDetailResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            id:
              type: string
            title:
              type: string
            topic:
              type: string
            theme:
              $ref: '#/components/schemas/PresentationTheme'
            slides:
              type: array
              items:
                $ref: '#/components/schemas/Slide'
            metadata:
              type: object
              properties:
                createdAt:
                  type: string
                  format: date-time
                updatedAt:
                  type: string
                  format: date-time
                slideCount:
                  type: integer
                language:
                  type: string
                generationModel:
                  type: string
            sharing:
              type: object
              properties:
                publicUrl:
                  type: string
                  format: uri
                embedCode:
                  type: string

    UpdatePresentationRequest:
      type: object
      properties:
        title:
          type: string
        theme:
          $ref: '#/components/schemas/PresentationTheme'
        slides:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              title:
                type: string
              content:
                type: object
              layout:
                $ref: '#/components/schemas/SlideLayout'

    ExportRequest:
      type: object
      required:
        - format
      properties:
        format:
          $ref: '#/components/schemas/ExportFormat'
        options:
          type: object
          properties:
            quality:
              type: string
              enum:
                - low
                - medium
                - high
              default: high
            includeNotes:
              type: boolean
              default: true
            slideRange:
              type: object
              properties:
                start:
                  type: integer
                end:
                  type: integer

    ExportResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            downloadUrl:
              type: string
              format: uri
              description: Download URL
            expiresAt:
              type: string
              format: date-time
            fileSize:
              type: integer
              description: File size (bytes)
            format:
              $ref: '#/components/schemas/ExportFormat'

    Template:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          type: string
        thumbnailUrl:
          type: string
          format: uri
        previewUrl:
          type: string
          format: uri
        theme:
          $ref: '#/components/schemas/PresentationTheme'
        slideCount:
          type: integer
        isPremium:
          type: boolean

    TemplatesResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            templates:
              type: array
              items:
                $ref: '#/components/schemas/Template'
            categories:
              type: array
              items:
                type: string
            pagination:
              type: object
              properties:
                total:
                  type: integer
                page:
                  type: integer
                limit:
                  type: integer
                hasMore:
                  type: boolean

    ErrorResponse:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        message:
          type: string
        code:
          type: string
        details:
          type: object

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    TooManyRequests:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - bearerAuth: []
