openapi: 3.0.0
info:
  title: Sketch to Video API
  version: 1.0.0
  description: |
    Sketch to Video Generation API - Convert sketches to images and then to short videos.

    ## Features
    - Sketch to image conversion
    - Image to video generation
    - Multiple motion effects
    - Audio track support
    - Session history tracking

    ## Workflow
    1. Upload sketch and generate image
    2. Configure video parameters (duration, motion, audio)
    3. Generate video from image
    4. Download completed video
  contact:
    name: CoreNovus API Support
    email: api@corenovus.com

servers:
  - url: https://api.corenovus.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

tags:
  - name: sketch-to-video
    description: Sketch to video generation operations
  - name: video-status
    description: Video generation status operations
  - name: session
    description: Session management operations

paths:
  /api/v1/sketch-to-video/generate-image:
    post:
      tags:
        - sketch-to-video
      summary: Generate image from sketch
      description: Convert a hand-drawn sketch or uploaded image with text description to a generated image
      operationId: generateImageFromSketch
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - description
              properties:
                sketchImage:
                  type: string
                  format: binary
                  description: Sketch image file (PNG, JPG, JPEG)
                sketchData:
                  type: string
                  description: Base64 encoded canvas drawing data
                description:
                  type: string
                  minLength: 1
                  maxLength: 1000
                  description: Text description of the desired image
                  example: A cute cat sitting on a sofa
                style:
                  $ref: '#/components/schemas/ImageStyle'
                resolution:
                  $ref: '#/components/schemas/ImageResolution'
                sessionId:
                  type: string
                  description: Session ID for tracking history
                  example: session_1234567890_abc123
            encoding:
              sketchImage:
                contentType: image/png, image/jpeg, image/jpg
      responses:
        '200':
          description: Image generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateImageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/sketch-to-video/image-to-video:
    post:
      tags:
        - sketch-to-video
      summary: Generate video from image
      description: Convert generated or uploaded image to a short video with optional motion and effects
      operationId: generateVideoFromImage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateVideoRequest'
      responses:
        '200':
          description: Video generation started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateVideoResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/sketch-to-video/video/{videoId}/status:
    get:
      tags:
        - video-status
      summary: Get video generation status
      description: Check the current status of video generation process
      operationId: getVideoStatus
      parameters:
        - name: videoId
          in: path
          required: true
          description: Video ID
          schema:
            type: string
            example: video_789xyz
      responses:
        '200':
          description: Status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/sketch-to-video/session/{sessionId}/history:
    get:
      tags:
        - session
      summary: Get session history
      description: Retrieve the generation history for a specific session
      operationId: getSessionHistory
      parameters:
        - name: sessionId
          in: path
          required: true
          description: Session ID
          schema:
            type: string
            example: session_1234567890_abc123
      responses:
        '200':
          description: History retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionHistoryResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ImageStyle:
      type: string
      enum:
        - realistic
        - anime
        - cartoon
        - artistic
        - sketch
        - watercolor
      default: realistic
      description: |
        Image generation style:
        - realistic: Photorealistic
        - anime: Anime style
        - cartoon: Cartoon style
        - artistic: Artistic interpretation
        - sketch: Sketch style
        - watercolor: Watercolor painting

    ImageResolution:
      type: string
      enum:
        - 512x512
        - 768x768
        - 1024x1024
        - 1024x576
        - 576x1024
      default: 1024x1024
      description: |
        Output resolution:
        - 512x512: Small square
        - 768x768: Medium square
        - 1024x1024: Large square
        - 1024x576: Landscape
        - 576x1024: Portrait

    MotionType:
      type: string
      enum:
        - zoom_in
        - zoom_out
        - pan_left
        - pan_right
        - ken_burns
        - rotate
        - parallax
        - none
      default: ken_burns
      description: |
        Motion effect type:
        - zoom_in: Zoom in
        - zoom_out: Zoom out
        - pan_left: Pan left
        - pan_right: Pan right
        - ken_burns: Ken Burns effect
        - rotate: Rotation
        - parallax: Parallax effect
        - none: No motion

    TransitionEffect:
      type: string
      enum:
        - fade
        - slide
        - zoom
        - none
      default: fade
      description: Transition effect

    AudioTrack:
      type: string
      enum:
        - ambient
        - upbeat
        - dramatic
        - peaceful
        - custom
        - none
      default: ambient
      description: Background audio track

    VideoFormat:
      type: string
      enum:
        - mp4
        - webm
        - avi
      default: mp4
      description: Video output format

    GenerationStatus:
      type: string
      enum:
        - queued
        - processing
        - completed
        - failed
      description: |
        Generation status:
        - queued: Waiting in queue
        - processing: Currently processing
        - completed: Successfully completed
        - failed: Failed

    GenerateVideoRequest:
      type: object
      properties:
        imageId:
          type: string
          description: ID of the generated image
          example: img_123456
        imageUrl:
          type: string
          format: uri
          description: URL of the image (alternative to imageId)
          example: https://storage.corenovus.com/generated/img_123456.png
        duration:
          type: integer
          minimum: 2
          maximum: 30
          default: 5
          description: Video duration in seconds
        motionType:
          $ref: '#/components/schemas/MotionType'
        transitionIn:
          $ref: '#/components/schemas/TransitionEffect'
        transitionOut:
          $ref: '#/components/schemas/TransitionEffect'
        audioTrack:
          $ref: '#/components/schemas/AudioTrack'
        fps:
          type: integer
          enum: [24, 30, 60]
          default: 30
          description: Frames per second
        format:
          $ref: '#/components/schemas/VideoFormat'
        sessionId:
          type: string
          description: Session ID for tracking history
          example: session_1234567890_abc123

    ImageMetadata:
      type: object
      properties:
        width:
          type: integer
          description: Image width (pixels)
          example: 1024
        height:
          type: integer
          description: Image height (pixels)
          example: 1024
        format:
          type: string
          description: Image format
          example: png
        size:
          type: integer
          description: File size (bytes)
          example: 2456789
        generationTime:
          type: number
          format: float
          description: Generation time (seconds)
          example: 3.5
        model:
          type: string
          description: AI model used
          example: stable-diffusion-xl

    VideoMetadata:
      type: object
      properties:
        duration:
          type: number
          description: Video duration (seconds)
          example: 5
        width:
          type: integer
          description: Video width (pixels)
          example: 1024
        height:
          type: integer
          description: Video height (pixels)
          example: 576
        format:
          type: string
          description: Video format
          example: mp4
        size:
          type: integer
          description: File size (bytes)
          example: 5242880
        fps:
          type: integer
          description: Frame rate
          example: 30

    GenerateImageResult:
      type: object
      required:
        - imageUrl
        - imageId
        - sessionId
      properties:
        imageUrl:
          type: string
          format: uri
          description: URL of the generated image
          example: https://storage.corenovus.com/generated/img_123456.png
        imageId:
          type: string
          description: Unique identifier for the generated image
          example: img_123456
        sessionId:
          type: string
          description: Session ID
          example: session_1234567890_abc123
        metadata:
          $ref: '#/components/schemas/ImageMetadata'

    GenerateVideoResult:
      type: object
      required:
        - videoId
        - status
        - sessionId
      properties:
        videoId:
          type: string
          description: Unique identifier for the video
          example: video_789xyz
        status:
          $ref: '#/components/schemas/GenerationStatus'
        estimatedTime:
          type: integer
          description: Estimated time to completion (seconds)
          example: 30
        sessionId:
          type: string
          description: Session ID
          example: session_1234567890_abc123
        videoUrl:
          type: string
          format: uri
          description: URL of the completed video (when status is completed)
          example: https://storage.corenovus.com/videos/video_789xyz.mp4
        error:
          type: string
          description: Error message (when status is failed)

    VideoStatusResult:
      type: object
      required:
        - videoId
        - status
      properties:
        videoId:
          type: string
          description: Video ID
          example: video_789xyz
        status:
          $ref: '#/components/schemas/GenerationStatus'
        progress:
          type: integer
          minimum: 0
          maximum: 100
          description: Progress percentage
          example: 65
        estimatedTimeRemaining:
          type: integer
          description: Estimated time remaining (seconds)
          example: 10
        videoUrl:
          type: string
          format: uri
          description: URL of the completed video
          example: https://storage.corenovus.com/videos/video_789xyz.mp4
        thumbnailUrl:
          type: string
          format: uri
          description: URL of the video thumbnail
          example: https://storage.corenovus.com/thumbnails/video_789xyz.jpg
        metadata:
          $ref: '#/components/schemas/VideoMetadata'
        error:
          type: string
          description: Error message (when status is failed)

    HistoryImageData:
      type: object
      properties:
        imageId:
          type: string
          example: img_123456
        imageUrl:
          type: string
          format: uri
          example: https://storage.corenovus.com/generated/img_123456.png
        style:
          type: string
          example: realistic
        resolution:
          type: string
          example: 1024x1024

    HistoryVideoData:
      type: object
      properties:
        videoId:
          type: string
          example: video_789xyz
        videoUrl:
          type: string
          format: uri
          example: https://storage.corenovus.com/videos/video_789xyz.mp4
        duration:
          type: number
          example: 5
        motionType:
          type: string
          example: ken_burns

    HistoryItem:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Generation timestamp
          example: "2024-03-20T10:30:00Z"
        type:
          type: string
          enum: [image, video]
          description: Type of generated content
        description:
          type: string
          description: User's description
          example: A cute cat sitting on a sofa
        imageData:
          $ref: '#/components/schemas/HistoryImageData'
        videoData:
          $ref: '#/components/schemas/HistoryVideoData'

    SessionHistoryResult:
      type: object
      required:
        - sessionId
        - history
      properties:
        sessionId:
          type: string
          description: Session ID
          example: session_1234567890_abc123
        history:
          type: array
          items:
            $ref: '#/components/schemas/HistoryItem'
          description: List of generation history items

    GenerateImageResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/GenerateImageResult'

    GenerateVideoResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/GenerateVideoResult'

    VideoStatusResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/VideoStatusResult'

    SessionHistoryResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/SessionHistoryResult'

    ApiResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
          description: Whether the request was successful
        error:
          type: string
          description: Error message (when success is false)
        message:
          type: string
          description: Additional message
        code:
          type: string
          description: Error code

    ErrorResponse:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: Generation failed
        message:
          type: string
          example: Failed to generate image from sketch
        code:
          type: string
          example: GENERATION_FAILED
        details:
          type: object
          description: Detailed error information

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    PayloadTooLarge:
      description: File too large (max 10MB)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    UnprocessableEntity:
      description: Cannot process content
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - bearerAuth: []
