openapi: 3.0.0
info:
  title: Speech to Text API
  version: 1.0.0
  description: |
    Speech to Text Service API - Convert audio to text with high accuracy.

    ## Features
    - Multiple audio format support (WAV, MP3, M4A, WebM, FLAC)
    - Real-time and batch transcription
    - Multi-language support (30+ languages)
    - Speaker diarization (identify different speakers)
    - Timestamp generation
    - Punctuation and formatting
    - Custom vocabulary support

    ## Supported Languages
    en-US, en-GB, zh-TW, zh-CN, ja-JP, ko-KR, es-ES, fr-FR, de-DE, and more.
  contact:
    name: CoreNovus API Support
    email: api@corenovus.com

servers:
  - url: https://api.corenovus.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

tags:
  - name: transcription
    description: Audio transcription operations
  - name: languages
    description: Language support operations
  - name: tasks
    description: Async task management

paths:
  /api/v1/speech-to-text/transcribe:
    post:
      tags:
        - transcription
      summary: Transcribe audio
      description: Convert audio file to text
      operationId: transcribeAudio
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - audio
              properties:
                audio:
                  type: string
                  format: binary
                  description: Audio file (WAV, MP3, M4A, WebM, FLAC)
                language:
                  type: string
                  description: Language code (e.g., en-US, zh-TW)
                  example: en-US
                autoDetectLanguage:
                  type: boolean
                  default: false
                  description: Auto-detect language
                enableTimestamps:
                  type: boolean
                  default: false
                  description: Include word-level timestamps
                enableSpeakerDiarization:
                  type: boolean
                  default: false
                  description: Identify different speakers
                speakerCount:
                  type: integer
                  minimum: 2
                  maximum: 10
                  description: Expected number of speakers (for diarization)
                vocabulary:
                  type: array
                  items:
                    type: string
                  description: Custom vocabulary words
                profanityFilter:
                  type: boolean
                  default: false
                  description: Filter profanity
          application/json:
            schema:
              type: object
              required:
                - audioData
              properties:
                audioData:
                  type: string
                  format: byte
                  description: Base64 encoded audio data
                audioFormat:
                  type: string
                  enum:
                    - wav
                    - mp3
                    - m4a
                    - webm
                    - flac
                  description: Audio format
                language:
                  type: string
                autoDetectLanguage:
                  type: boolean
                  default: false
                enableTimestamps:
                  type: boolean
                  default: false
                enableSpeakerDiarization:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Transcription completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranscribeResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/speech-to-text/transcribe-async:
    post:
      tags:
        - transcription
      summary: Transcribe audio (async)
      description: |
        Start async transcription for long audio files.

        Use this endpoint for audio longer than 5 minutes.
        Returns a task ID for status polling.
      operationId: transcribeAudioAsync
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - audio
              properties:
                audio:
                  type: string
                  format: binary
                language:
                  type: string
                autoDetectLanguage:
                  type: boolean
                  default: false
                enableTimestamps:
                  type: boolean
                  default: true
                enableSpeakerDiarization:
                  type: boolean
                  default: false
                speakerCount:
                  type: integer
                callbackUrl:
                  type: string
                  format: uri
                  description: Webhook URL for completion notification
      responses:
        '202':
          description: Task accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncTaskResponse'

  /api/v1/speech-to-text/tasks/{taskId}:
    get:
      tags:
        - tasks
      summary: Get task status
      description: Check the status of an async transcription task
      operationId: getTaskStatus
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
          description: Task ID
      responses:
        '200':
          description: Task status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/speech-to-text/stream:
    post:
      tags:
        - transcription
      summary: Real-time transcription
      description: |
        Stream audio for real-time transcription via WebSocket.

        This endpoint upgrades to WebSocket connection.
        Send audio chunks and receive transcription in real-time.
      operationId: streamTranscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - language
              properties:
                language:
                  type: string
                  description: Language code
                interimResults:
                  type: boolean
                  default: true
                  description: Include interim (partial) results
                sampleRate:
                  type: integer
                  default: 16000
                  description: Audio sample rate (Hz)
      responses:
        '101':
          description: Switching to WebSocket
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/v1/speech-to-text/languages:
    get:
      tags:
        - languages
      summary: Get supported languages
      description: List all supported languages for transcription
      operationId: getLanguages
      responses:
        '200':
          description: Languages retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguagesResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TranscribeResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                text:
                  type: string
                  description: Full transcribed text
                language:
                  type: string
                  description: Detected or specified language
                confidence:
                  type: number
                  format: float
                  minimum: 0
                  maximum: 1
                  description: Overall confidence score
                duration:
                  type: number
                  format: float
                  description: Audio duration (seconds)
                words:
                  type: array
                  items:
                    $ref: '#/components/schemas/TranscribedWord'
                  description: Word-level details (if timestamps enabled)
                speakers:
                  type: array
                  items:
                    $ref: '#/components/schemas/SpeakerSegment'
                  description: Speaker segments (if diarization enabled)
                metadata:
                  $ref: '#/components/schemas/TranscriptionMetadata'

    TranscribedWord:
      type: object
      properties:
        word:
          type: string
        startTime:
          type: number
          format: float
          description: Start time (seconds)
        endTime:
          type: number
          format: float
          description: End time (seconds)
        confidence:
          type: number
          format: float
        speaker:
          type: string
          description: Speaker ID (if diarization enabled)

    SpeakerSegment:
      type: object
      properties:
        speaker:
          type: string
          description: Speaker identifier (e.g., "Speaker 1")
        startTime:
          type: number
          format: float
        endTime:
          type: number
          format: float
        text:
          type: string
          description: Text spoken by this speaker

    AsyncTaskResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                taskId:
                  type: string
                  description: Task ID for status polling
                status:
                  type: string
                  enum:
                    - queued
                    - processing
                  description: Initial task status
                estimatedTime:
                  type: integer
                  description: Estimated completion time (seconds)

    TaskStatusResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                taskId:
                  type: string
                status:
                  type: string
                  enum:
                    - queued
                    - processing
                    - completed
                    - failed
                progress:
                  type: integer
                  minimum: 0
                  maximum: 100
                  description: Progress percentage
                result:
                  type: object
                  description: Transcription result (when completed)
                  properties:
                    text:
                      type: string
                    language:
                      type: string
                    confidence:
                      type: number
                      format: float
                    duration:
                      type: number
                      format: float
                    words:
                      type: array
                      items:
                        $ref: '#/components/schemas/TranscribedWord'
                    speakers:
                      type: array
                      items:
                        $ref: '#/components/schemas/SpeakerSegment'
                error:
                  type: string
                  description: Error message (when failed)
                createdAt:
                  type: string
                  format: date-time
                completedAt:
                  type: string
                  format: date-time

    LanguagesResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    description: Language code (e.g., en-US)
                  name:
                    type: string
                    description: Language name
                  nativeName:
                    type: string
                    description: Native language name
                  supportedFeatures:
                    type: object
                    properties:
                      transcription:
                        type: boolean
                      diarization:
                        type: boolean
                      punctuation:
                        type: boolean

    TranscriptionMetadata:
      type: object
      properties:
        model:
          type: string
          description: Model used
        processingTime:
          type: number
          format: float
          description: Processing time (seconds)
        audioFormat:
          type: string
        sampleRate:
          type: integer
        channels:
          type: integer

    ApiResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        error:
          type: string
        message:
          type: string
        code:
          type: string

    ErrorResponse:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        message:
          type: string
        code:
          type: string
        details:
          type: object

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    PayloadTooLarge:
      description: File too large (max 100MB)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - bearerAuth: []
