openapi: 3.0.0
info:
  title: Speech to Image API
  version: 1.0.0
  description: |
    Speech to Image Generation API - Convert voice descriptions into images.

    ## Features
    - Voice input to image generation
    - Multiple audio format support (WAV, MP3, M4A, WebM)
    - Various image styles (realistic, artistic, cartoon, etc.)
    - Customizable image size and quality
    - Batch image generation
    - Task progress tracking
  contact:
    name: CoreNovus API Support
    email: api@corenovus.com

servers:
  - url: https://api.corenovus.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

tags:
  - name: speech-to-image
    description: Speech to image generation operations
  - name: image-styles
    description: Image style operations
  - name: generation-tasks
    description: Generation task management

paths:
  /api/v1/speech-to-image/generate:
    post:
      tags:
        - speech-to-image
      summary: Generate image from speech
      description: Upload audio file or data, transcribe to text, and generate image
      operationId: generateImage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - audio
                - imageStyle
                - language
              properties:
                audio:
                  type: string
                  format: binary
                  description: Audio file (WAV, MP3, M4A, WebM)
                imageStyle:
                  type: string
                  enum:
                    - realistic
                    - artistic
                    - cartoon
                    - abstract
                    - fantasy
                    - minimalist
                    - vintage
                    - futuristic
                  description: Image style
                language:
                  type: string
                  enum:
                    - en-US
                    - en-GB
                    - es-ES
                    - fr-FR
                    - de-DE
                    - it-IT
                    - pt-BR
                    - ja-JP
                    - ko-KR
                    - zh-TW
                    - zh-CN
                  description: Speech recognition language
                userQuestion:
                  type: string
                  maxLength: 1000
                  description: User question (optional)
                options:
                  type: object
                  properties:
                    size:
                      type: string
                      enum:
                        - 512x512
                        - 1024x1024
                        - 1024x1792
                        - 1792x1024
                      default: 1024x1024
                      description: Image size
                    quality:
                      type: string
                      enum:
                        - standard
                        - hd
                        - ultra
                      default: standard
                      description: Image quality
                    numberOfImages:
                      type: integer
                      minimum: 1
                      maximum: 4
                      default: 1
                      description: Number of images to generate
          application/json:
            schema:
              type: object
              required:
                - audioData
                - imageStyle
                - language
              properties:
                audioData:
                  type: string
                  format: byte
                  description: Base64 encoded audio data
                imageStyle:
                  type: string
                  enum:
                    - realistic
                    - artistic
                    - cartoon
                    - abstract
                    - fantasy
                    - minimalist
                    - vintage
                    - futuristic
                language:
                  type: string
                  enum:
                    - en-US
                    - en-GB
                    - es-ES
                    - fr-FR
                    - de-DE
                    - it-IT
                    - pt-BR
                    - ja-JP
                    - ko-KR
                    - zh-TW
                    - zh-CN
                audioFormat:
                  type: string
                  enum:
                    - wav
                    - mp3
                    - m4a
                    - webm
                  description: Audio format
                voiceDescription:
                  type: string
                  description: Direct text description (skip speech recognition)
                userQuestion:
                  type: string
                options:
                  $ref: '#/components/schemas/ImageGenerationOptions'
      responses:
        '200':
          description: Image generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateImageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/speech-to-image/generate-batch:
    post:
      tags:
        - speech-to-image
      summary: Batch image generation
      description: Generate multiple image variations from voice description
      operationId: generateBatch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchGenerationRequest'
      responses:
        '202':
          description: Batch task accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchGenerationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/speech-to-image/generation/{taskId}:
    get:
      tags:
        - generation-tasks
      summary: Get generation task status
      description: Check batch generation task progress and results
      operationId: getGenerationStatus
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
          description: Generation task ID
      responses:
        '200':
          description: Task status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerationTaskStatus'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/speech-to-image/styles:
    get:
      tags:
        - image-styles
      summary: Get supported image styles
      description: Retrieve all supported image styles and their details
      operationId: getImageStyles
      responses:
        '200':
          description: Styles retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageStylesResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ImageGenerationOptions:
      type: object
      properties:
        size:
          type: string
          enum:
            - 512x512
            - 1024x1024
            - 1024x1792
            - 1792x1024
          default: 1024x1024
          description: Image size
        quality:
          type: string
          enum:
            - standard
            - hd
            - ultra
          default: standard
          description: Image quality
        numberOfImages:
          type: integer
          minimum: 1
          maximum: 4
          default: 1
          description: Number of images to generate
        negativePrompt:
          type: string
          description: Elements to avoid in the image
        seed:
          type: integer
          description: Random seed (for reproducible results)
        guidanceScale:
          type: number
          format: float
          minimum: 1
          maximum: 20
          default: 7.5
          description: How closely to follow the prompt

    GeneratedImage:
      type: object
      required:
        - url
        - format
        - size
      properties:
        url:
          type: string
          format: uri
          description: Image URL
        base64:
          type: string
          format: byte
          description: Base64 encoded image data (optional)
        format:
          type: string
          enum:
            - png
            - jpg
            - webp
          description: Image format
        size:
          type: string
          description: Image size (e.g., 1024x1024)
        metadata:
          type: object
          properties:
            seed:
              type: integer
              description: Random seed used
            model:
              type: string
              description: Model version
            revisedPrompt:
              type: string
              description: Optimized prompt

    GenerateImageResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              required:
                - images
              properties:
                images:
                  type: array
                  items:
                    $ref: '#/components/schemas/GeneratedImage'
                  description: Generated images
                transcription:
                  type: string
                  description: Speech transcription result
                prompt:
                  type: string
                  description: Optimized prompt used for generation
                response:
                  type: string
                  description: AI response to user question (if provided)
                metadata:
                  type: object
                  properties:
                    generationTime:
                      type: number
                      format: float
                      description: Generation time (seconds)
                    model:
                      type: string
                      description: Image generation model
                    style:
                      type: string
                      description: Image style used
                    transcriptionConfidence:
                      type: number
                      format: float
                      description: Speech recognition confidence
                    contentWarning:
                      type: boolean
                      description: Contains sensitive content warning

    BatchGenerationRequest:
      type: object
      required:
        - description
        - imageStyle
        - variations
      properties:
        description:
          type: string
          description: Image description (text or previous transcription)
        imageStyle:
          type: string
          enum:
            - realistic
            - artistic
            - cartoon
            - abstract
            - fantasy
            - minimalist
            - vintage
            - futuristic
          description: Base image style
        variations:
          type: array
          minItems: 2
          maxItems: 10
          items:
            type: object
            properties:
              styleModifier:
                type: string
                description: Style modifier
              colorScheme:
                type: string
                description: Color scheme
              mood:
                type: string
                description: Mood/atmosphere
        baseOptions:
          $ref: '#/components/schemas/ImageGenerationOptions'

    BatchGenerationResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                taskId:
                  type: string
                  description: Batch task ID
                status:
                  type: string
                  enum:
                    - queued
                    - processing
                    - completed
                    - failed
                  description: Task status
                totalImages:
                  type: integer
                  description: Total images to generate
                estimatedTime:
                  type: integer
                  description: Estimated completion time (seconds)

    GenerationTaskStatus:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                taskId:
                  type: string
                  description: Task ID
                status:
                  type: string
                  enum:
                    - queued
                    - processing
                    - completed
                    - failed
                  description: Task status
                progress:
                  type: integer
                  minimum: 0
                  maximum: 100
                  description: Progress percentage
                completedImages:
                  type: integer
                  description: Images completed
                totalImages:
                  type: integer
                  description: Total images
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/GeneratedImage'
                  description: Generated images (so far)
                errors:
                  type: array
                  items:
                    type: object
                    properties:
                      index:
                        type: integer
                      error:
                        type: string
                      code:
                        type: string

    ImageStyleInfo:
      type: object
      properties:
        id:
          type: string
          description: Style ID
        name:
          type: string
          description: Style name
        displayName:
          type: string
          description: Display name
        description:
          type: string
          description: Style description
        examples:
          type: array
          items:
            type: string
          description: Example image URLs
        tags:
          type: array
          items:
            type: string
          description: Related tags
        settings:
          type: object
          description: Recommended settings
          properties:
            recommendedSize:
              type: string
            recommendedQuality:
              type: string
            guidanceScale:
              type: number

    ImageStylesResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                styles:
                  type: array
                  items:
                    $ref: '#/components/schemas/ImageStyleInfo'
                categories:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      styles:
                        type: array
                        items:
                          type: string

    ApiResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
          description: Request success status
        error:
          type: string
          description: Error message (when success is false)
        message:
          type: string
          description: Additional message
        code:
          type: string
          description: Error code

    ErrorResponse:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        message:
          type: string
        code:
          type: string
        details:
          type: object
          description: Detailed error information

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    PayloadTooLarge:
      description: File too large (max 25MB)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    UnprocessableEntity:
      description: Unable to process content (e.g., inappropriate content)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - bearerAuth: []
