openapi: 3.0.0
info:
  title: Translation API
  version: 1.0.0
  description: |
    AI Translation Service API - Translate text and documents between languages.

    ## Features
    - Language detection
    - Text translation with multiple style options
    - Document translation (txt, md, pdf, docx)
    - Multiple translation alternatives
    - Terminology extraction
    - Task-based async processing

servers:
  - url: https://api.corenovus.com
    description: Production server
  - url: http://localhost:3000
    description: Development server

tags:
  - name: translation
    description: Translation operations

paths:
  /api/v1/translation/detect-language:
    post:
      summary: Detect language
      description: Automatically detect the language of input text
      operationId: detectLanguage
      tags:
        - translation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectLanguageRequest'
      responses:
        '200':
          description: Language detected successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetectLanguageResponse'

  /api/v1/translation/translate:
    post:
      summary: Translate text
      description: Translate text from source to target language with configurable style and domain
      operationId: translateText
      tags:
        - translation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslateTextRequest'
      responses:
        '201':
          description: Translation completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslateTextResponse'

  /api/v1/translation/upload-document:
    post:
      summary: Upload document for translation
      description: |
        Upload a document file for translation.

        Supported formats: txt, md, pdf, docx
      operationId: uploadDocument
      tags:
        - translation
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadDocumentRequest'
      responses:
        '201':
          description: Document uploaded, translation started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadDocumentResponse'
        '400':
          description: Invalid file or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/translation/tasks/{taskId}:
    get:
      summary: Get translation task status
      description: Check the status and progress of a translation task
      operationId: getTaskStatus
      tags:
        - translation
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
          description: Translation task ID
      responses:
        '200':
          description: Task status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatusResponse'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/translation/tasks/{taskId}/download:
    get:
      summary: Download translated file
      description: Download the translated document file
      operationId: downloadTranslatedFile
      tags:
        - translation
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
          description: Translation task ID
      responses:
        '200':
          description: File download
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: File not found or task not completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    DetectLanguageRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          minLength: 1
          description: Text to analyze for language detection
        confidenceThreshold:
          type: number
          minimum: 0
          maximum: 1
          description: Minimum confidence threshold (0-1)

    DetectLanguageResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            detectedLanguage:
              $ref: '#/components/schemas/DetectedLanguage'

    DetectedLanguage:
      type: object
      required:
        - code
        - name
        - confidence
      properties:
        code:
          type: string
          description: Language code (e.g., 'en', 'zh-TW')
        name:
          type: string
          description: Language name
        confidence:
          type: number
          description: Detection confidence score (0-1)
        flag:
          type: string
          description: Country flag emoji

    TranslateTextRequest:
      type: object
      required:
        - sourceText
        - sourceLang
        - targetLang
        - translationConfig
      properties:
        sourceText:
          type: string
          minLength: 1
          description: Text to translate
        sourceLang:
          type: string
          description: Source language code (e.g., 'zh-TW', 'en', 'auto')
        targetLang:
          type: string
          description: Target language code (e.g., 'en', 'zh-CN')
        translationConfig:
          $ref: '#/components/schemas/TranslationConfig'

    TranslationConfig:
      type: object
      required:
        - style
        - domain
        - model
      properties:
        style:
          type: string
          enum:
            - formal
            - casual
            - academic
            - technical
          description: |
            Translation style:
            - formal: Professional/business tone
            - casual: Conversational tone
            - academic: Scholarly writing style
            - technical: Technical documentation style
        domain:
          type: string
          enum:
            - general
            - business
            - technical
            - medical
            - legal
            - academic
            - literature
          description: Domain/field for specialized terminology
        model:
          type: string
          enum:
            - translation-llm
            - nmt
            - gemini
          description: |
            Translation model:
            - translation-llm: LLM-based translation
            - nmt: Neural machine translation
            - gemini: Google Gemini model
        multipleOptions:
          type: boolean
          default: true
          description: Provide multiple translation alternatives
        includeTerminology:
          type: boolean
          default: false
          description: Include terminology explanations

    TranslateTextResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            taskId:
              type: string
              description: Translation task ID
            translations:
              $ref: '#/components/schemas/Translations'
            terminology:
              type: array
              items:
                $ref: '#/components/schemas/Terminology'

    Translations:
      type: object
      properties:
        main:
          $ref: '#/components/schemas/MainTranslation'
        alternatives:
          type: array
          description: Alternative translation options
          items:
            $ref: '#/components/schemas/AlternativeTranslation'

    MainTranslation:
      type: object
      properties:
        text:
          type: string
          description: Primary translation result
        confidence:
          type: number
          description: Translation confidence score
        model:
          type: string
          description: Model used for translation
        processingTime:
          type: number
          description: Processing time in seconds

    AlternativeTranslation:
      type: object
      properties:
        text:
          type: string
        confidence:
          type: number
        style:
          type: string

    Terminology:
      type: object
      properties:
        term:
          type: string
          description: Technical term
        sourceExplanation:
          type: string
          description: Explanation in source language
        targetExplanation:
          type: string
          description: Explanation in target language
        context:
          type: string
          description: Usage context

    UploadDocumentRequest:
      type: object
      required:
        - file
        - sourceLang
        - targetLang
        - translationConfig
      properties:
        file:
          type: string
          format: binary
          description: Document file (txt, md, pdf, docx)
        sourceLang:
          type: string
          description: Source language code
        targetLang:
          type: string
          description: Target language code
        translationConfig:
          type: string
          description: Translation config (JSON string)

    UploadDocumentResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            taskId:
              type: string
              description: Translation task ID
            fileName:
              type: string
              description: Original file name
            fileSize:
              type: number
              description: File size in bytes
            fileType:
              type: string
              description: File type
            estimatedTime:
              type: number
              description: Estimated processing time (seconds)
            status:
              $ref: '#/components/schemas/TaskStatus'

    TaskStatusResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            taskId:
              type: string
            status:
              $ref: '#/components/schemas/TaskStatus'
            progress:
              type: number
              minimum: 0
              maximum: 100
              description: Processing progress (%)
            result:
              $ref: '#/components/schemas/TaskResult'
            error:
              $ref: '#/components/schemas/TaskError'
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time

    TaskStatus:
      type: string
      enum:
        - pending
        - processing
        - completed
        - failed
      description: Task status

    TaskResult:
      type: object
      description: Translation result (only when completed)
      properties:
        translatedText:
          type: string
          description: Translated text
        translatedFileUrl:
          type: string
          description: Download URL for translated file
        wordCount:
          type: object
          properties:
            source:
              type: number
            target:
              type: number
        terminology:
          type: array
          items:
            $ref: '#/components/schemas/Terminology'

    TaskError:
      type: object
      description: Error info (only when failed)
      properties:
        message:
          type: string
        code:
          type: string

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        error:
          type: string
        code:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
