openapi: 3.0.0
info:
  title: AI Travel Planning API
  version: 1.0.0
  description: |
    AI Travel Planning Service API - Get personalized travel recommendations.

    ## Features
    - AI-powered travel planning
    - Multiple travel types (leisure, business, adventure, etc.)
    - Streaming responses
    - Travel templates
    - Destination information
    - Budget planning
    - Itinerary generation
  contact:
    name: CoreNovus API Support
    email: api@corenovus.com

servers:
  - url: https://api.corenovus.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

tags:
  - name: travel-planning
    description: AI travel planning operations
  - name: templates
    description: Travel template operations
  - name: destinations
    description: Destination information

paths:
  /api/v1/travel/planning:
    post:
      tags:
        - travel-planning
      summary: AI travel planning
      description: Get personalized travel suggestions and planning based on preferences
      operationId: submitTravelPlanning
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TravelPlanningRequest'
      responses:
        '200':
          description: Planning completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TravelPlanningResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/travel/planning/stream:
    post:
      tags:
        - travel-planning
      summary: AI travel planning (streaming)
      description: Get travel planning suggestions via Server-Sent Events
      operationId: streamTravelPlanning
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TravelPlanningRequest'
      responses:
        '200':
          description: Stream started
          content:
            text/event-stream:
              schema:
                type: string
                format: binary
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/travel/templates:
    get:
      tags:
        - templates
      summary: Get travel templates
      description: Retrieve preset travel itinerary templates
      operationId: getTemplates
      parameters:
        - name: destination
          in: query
          description: Destination name
          schema:
            type: string
        - name: travelType
          in: query
          description: Travel type
          schema:
            $ref: '#/components/schemas/TravelType'
        - name: duration
          in: query
          description: Trip duration (days)
          schema:
            type: integer
            minimum: 1
            maximum: 30
      responses:
        '200':
          description: Templates retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      templates:
                        type: array
                        items:
                          $ref: '#/components/schemas/TravelTemplate'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/travel/destination/{name}:
    get:
      tags:
        - destinations
      summary: Get destination info
      description: Get detailed information about a destination
      operationId: getDestinationInfo
      parameters:
        - name: name
          in: path
          required: true
          description: Destination name
          schema:
            type: string
      responses:
        '200':
          description: Destination info retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/DestinationInfo'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TravelType:
      type: string
      enum:
        - leisure
        - business
        - adventure
        - cultural
        - family
        - romantic
        - budget
        - luxury
      description: |
        Travel type:
        - leisure: Relaxation and sightseeing
        - business: Business trips
        - adventure: Adventure and outdoor activities
        - cultural: Cultural experiences
        - family: Family-friendly trips
        - romantic: Romantic getaways
        - budget: Budget-conscious travel
        - luxury: Luxury experiences

    QuickFeature:
      type: string
      enum:
        - itinerary
        - accommodation
        - activities
        - transportation
      description: Quick feature type

    TravelPlanningRequest:
      type: object
      required:
        - travelType
      properties:
        travelType:
          $ref: '#/components/schemas/TravelType'
        quickFeatures:
          type: array
          items:
            $ref: '#/components/schemas/QuickFeature'
          description: Quick feature options
        userQuestion:
          type: string
          maxLength: 1000
          description: User's travel question
        duration:
          type: object
          properties:
            days:
              type: integer
              minimum: 1
              maximum: 365
              description: Number of days
            nights:
              type: integer
              minimum: 0
              maximum: 364
              description: Number of nights
        departureDate:
          type: string
          format: date
          description: Departure date
        returnDate:
          type: string
          format: date
          description: Return date
        context:
          type: object
          properties:
            budget:
              type: string
              description: Budget level
            budgetAmount:
              type: object
              properties:
                min:
                  type: number
                  description: Minimum budget
                max:
                  type: number
                  description: Maximum budget
                currency:
                  type: string
                  description: Currency code
            travelers:
              type: integer
              minimum: 1
              maximum: 100
              description: Number of travelers
            preferences:
              type: array
              items:
                type: string
              description: Preferences
            specialRequirements:
              type: array
              items:
                type: string
              description: Special requirements

    TravelPlanningResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              required:
                - response
              properties:
                response:
                  type: string
                  description: AI-generated travel planning response
                suggestions:
                  type: array
                  items:
                    type: string
                  description: Follow-up suggestion questions
                metadata:
                  type: object
                  properties:
                    confidence:
                      type: number
                      format: float
                      minimum: 0
                      maximum: 1
                      description: Response confidence
                    processingTime:
                      type: number
                      format: float
                      description: Processing time (seconds)
                    model:
                      type: string
                      description: AI model used
                    provider:
                      type: string
                      description: AI provider
                    tokens:
                      type: object
                      properties:
                        input:
                          type: integer
                          description: Input tokens
                        output:
                          type: integer
                          description: Output tokens
                relatedContent:
                  type: object
                  properties:
                    articles:
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          url:
                            type: string
                            format: uri
                          type:
                            type: string
                            enum:
                              - blog
                              - guide
                              - tips
                    destinations:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string
                          rating:
                            type: number
                            format: float
                            minimum: 0
                            maximum: 5
                structuredPlan:
                  $ref: '#/components/schemas/TravelStructuredPlan'

    TravelStructuredPlan:
      type: object
      properties:
        overview:
          type: object
          properties:
            destination:
              type: string
            duration:
              type: string
            highlights:
              type: array
              items:
                type: string
            totalBudget:
              type: object
              properties:
                estimated:
                  type: number
                currency:
                  type: string
                perPerson:
                  type: boolean
        itinerary:
          type: array
          items:
            $ref: '#/components/schemas/TravelItineraryDay'
        budget:
          $ref: '#/components/schemas/TravelBudget'
        tips:
          $ref: '#/components/schemas/TravelTips'

    TravelItineraryDay:
      type: object
      properties:
        dayNumber:
          type: integer
        date:
          type: string
          format: date
        theme:
          type: string
        location:
          type: string
        activities:
          type: array
          items:
            type: object
            properties:
              time:
                type: string
              name:
                type: string
              description:
                type: string
              duration:
                type: string
              cost:
                type: number
              tips:
                type: string
        meals:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum:
                  - breakfast
                  - lunch
                  - dinner
                  - snack
              restaurant:
                type: string
              specialty:
                type: string
              estimatedCost:
                type: number
        accommodation:
          type: object
          properties:
            name:
              type: string
            type:
              type: string
            area:
              type: string
            pricePerNight:
              type: number
        transportation:
          type: array
          items:
            type: object
            properties:
              from:
                type: string
              to:
                type: string
              method:
                type: string
              duration:
                type: string
              cost:
                type: number

    TravelBudget:
      type: object
      properties:
        total:
          type: number
        currency:
          type: string
        breakdown:
          type: object
          properties:
            accommodation:
              $ref: '#/components/schemas/BudgetCategory'
            transportation:
              $ref: '#/components/schemas/BudgetCategory'
            meals:
              $ref: '#/components/schemas/BudgetCategory'
            activities:
              $ref: '#/components/schemas/BudgetCategory'
            shopping:
              $ref: '#/components/schemas/BudgetCategory'
            others:
              $ref: '#/components/schemas/BudgetCategory'

    BudgetCategory:
      type: object
      properties:
        amount:
          type: number
        percentage:
          type: number
          format: float
          minimum: 0
          maximum: 100
        details:
          type: array
          items:
            type: string

    TravelTips:
      type: object
      properties:
        cultural:
          type: array
          items:
            type: string
          description: Cultural tips
        safety:
          type: array
          items:
            type: string
          description: Safety tips
        practical:
          type: array
          items:
            type: string
          description: Practical tips
        bestTime:
          type: string
          description: Best time to visit
        mustHave:
          type: array
          items:
            type: string
          description: Must-have items

    TravelTemplate:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        destination:
          type: string
        duration:
          type: object
          properties:
            days:
              type: integer
            nights:
              type: integer
        travelType:
          $ref: '#/components/schemas/TravelType'
        estimatedBudget:
          type: object
          properties:
            min:
              type: number
            max:
              type: number
            currency:
              type: string
        highlights:
          type: array
          items:
            type: string
        popularityScore:
          type: number
          format: float
          minimum: 0
          maximum: 100

    DestinationInfo:
      type: object
      properties:
        name:
          type: string
        country:
          type: string
        region:
          type: string
        description:
          type: string
        climate:
          type: object
          properties:
            type:
              type: string
            bestMonths:
              type: array
              items:
                type: integer
                minimum: 1
                maximum: 12
            averageTemperature:
              type: object
              additionalProperties:
                type: number
        currency:
          type: object
          properties:
            code:
              type: string
            name:
              type: string
            exchangeRate:
              type: number
        language:
          type: array
          items:
            type: string
        timezone:
          type: string
        attractions:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              type:
                type: string
              description:
                type: string
              rating:
                type: number
                format: float
                minimum: 0
                maximum: 5
        transportation:
          type: object
          properties:
            airport:
              type: array
              items:
                type: object
            publicTransport:
              type: array
              items:
                type: string
        safety:
          type: object
          properties:
            level:
              type: string
              enum:
                - very_safe
                - safe
                - moderate
                - caution
            tips:
              type: array
              items:
                type: string

    ApiResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
          description: Request success status
        error:
          type: string
          description: Error message (when success is false)
        message:
          type: string
          description: Additional message
        code:
          type: string
          description: Error code

    ErrorResponse:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        message:
          type: string
        code:
          type: string
        details:
          type: object
          description: Detailed error information

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    TooManyRequests:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - bearerAuth: []
